### ISSUE TITLE
File formats and OpenBabel

### ISSUE THREAD

**Issue by jnoske** [gregory-kyro/HAC-Net#4]
Hi I have some questions regarding the input for HAC-Net,

First: For the ligand do I need to assign partial charges myself or is it done automatically in the predict_pkd function?
Second: I get a lot of these warnings from OpenBabel: This Mol2 file is non-standard. Problem with molecule: pocket Cannot interpret atom types correctly, instead attempting to interpret atom type: O as elements instead. 
Is this comming from the pdb or the mol2 ligand file?

I would be happy to get help.

Best,
Jakob

**Comment by gregory-kyro** [comment]
Hi Jakob,

1) As the code is currently written, the ligand MOL2 file is expected to contain atomic partial charges. However, you can easily calculate charges for your ligand file with [ACC2 ](https://acc2.ncbr.muni.cz/). 

2) This can be coming from either the ligand or protein file, given that they are both in MOL2 format at the point of being processed by openbabel. We would be happy to help if you can provide more information or the files you are attempting to use.

I hope this helps to resolve your issues. Please feel free to reach out with any other questions or concerns!

Best,
Gregory

**Comment by jnoske** [comment]
Hi gregory,

Find the files I am trying to process attached.
[files.zip](https://github.com/gregory-kyro/HAC-Net/files/12216446/files.zip)

**Comment by jnoske** [comment]
I think it is due to the formatting from ACC2. The lines in the file seem to have a different orientation (centered). If I omit the step openbabel reads it without any error.

**Comment by gregory-kyro** [comment]
Hi Jakob,

After investigating your case, we are able to fix the problem by adding the file name without extension ('ligand') under `@<TRIPOS>MOLECULE` in the text of the mol2 file. Please let me know if you have any other questions!

Best,
Gregory

**Comment by jnoske** [comment]
Hi Gregory,

Thank you for the fast help! Could you explain or give an example how you generally prepare input files for HAC-Net, since I get similar warnings for the receptor.

Best,
Jakob

**Comment by gregory-kyro** [comment]
Hi Jakob,

Input files are prepared according to this procedure:

## Procedure for Processing and Preparing Data

### 1) Read in PDBbind dataset and create a csv file to be used to produce hdf5 files
  - **parse_data.py**
        
### 2) Add hydrogens to pocket PDB files and convert to mol2 file type using Chimera 1.16, remove TIP3P atoms from mol2 files
  - **add_H_and_mol2_chimera.py**
  - **remove_tip3p_chimera.sh**
  
### 3) Compute charges for mol2 files externally with Atomic Charge Calculator II (ACC2)
  - **ACC2: <https://acc2.ncbr.muni.cz/>**

### 4) Create hdf file
  - **create_hdf.py**
  
### 5) Subdivide hdf file into train, validation, and test sets
  
### 6) Create hdf files containing voxelized train, test, and validation data for use in the 3D-CNN
  - **create_voxelized_hdf.py**

Please let me know if you have any other questions; I am happy to help.

Best,
Gregory
