### ISSUE TITLE
unable to find the HACNet.ipynb

### ISSUE THREAD

**Issue by Neo-Flash** [gregory-kyro/HAC-Net#6]
Hello! 

Thank you for sharing your work. I am unable to find the HACNet.ipynb that you demonstrated in your teaching video.

 Could you please upload it again? Thank you!

**Comment by gregory-kyro** [comment]
Hello,

We are working on an updated notebook that addresses some bugs that have arisen due to changes in libraries that the HAC-Net package relies on. We will upload the updated notebook in the near future!

Best,
Gregory

**Comment by Tonylac77** [comment]
Hi and thanks for this great work! Any timeline on this? Would love to integrate HACNet in my own workflows!

**Comment by gregory-kyro** [comment]
Hi Antoine,

We have put this aside, as we are currently working on HAC-Net v2. We hope to have HAC-Net v2 available in the near future, and will provide a Google Colab notebook to facilitate implementation of the trained model.

You should be able to use HAC-Net via the source code provided in this repository. I would be happy to help if you have any questions! :)

Best,
Gregory
