### ISSUE TITLE
How to train 2 GCNs?

### ISSUE THREAD

**Issue by yuwang-langrui** [gregory-kyro/HAC-Net#8]
Hello Gregory, 
First of all, thank you very much for sharing this amazing work. 
I have a question while trying to run your code. Your paper mentions that you trained two GCN networks, and I also noticed that the prediction examples show the use of parameters from two GCNs. However, I am not sure how to train two different GCNs. Should I train the dataset twice? Or have I misunderstood something? I hope to get your response.

Regards,

**Comment by gregory-kyro** [comment]
Hello,

We train two GCNs separately; the architecture and training data are identical for both cases. Simply train the same architecture twice with the same data, and you will obtain two sets of slightly different parameters.

I hope this helps. Please feel free to reach out with any additional questions.

Best,
Gregory
